name: K6 Performance Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  k6-performance-tests:
    name: Run K6 Performance Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install K6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz | tar xvz
          sudo cp k6-v0.49.0-linux-amd64/k6 /usr/local/bin
      
      - name: Create results directory
        run: mkdir -p results
      
      - name: Make validate-results.js executable
        run: chmod +x validate-results.js
      
      - name: Run Basic Test
        run: |
          echo "Running basic test with CI configuration"
          k6 run --out json=results/basic-test-result.json dummyjson-test.js --duration 30s --vus 5
        
      - name: Run Advanced Test
        run: |
          echo "Running advanced test with CI configuration"
          k6 run --out json=results/advanced-test-result.json dummyjson-advanced-test.js --duration 30s --vus 5
      
      - name: Analyze Results
        run: |
          echo "Basic Test Results"
          node analyze-results.js results/basic-test-result.json
          echo ""
          echo "Advanced Test Results"
          node analyze-results.js results/advanced-test-result.json
      
      - name: Validate Results
        run: |
          echo "Validating test results against CI thresholds"
          node validate-results.js results/basic-test-result.json --ci
          node validate-results.js results/advanced-test-result.json --ci
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: k6-test-results
          path: results/
          retention-days: 7
